spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_db
spring.datasource.username=postgres
spring.datasource.password=Elyse@1234

# Create tables from @Entity first, then run data.sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.show-sql=true

# Swagger (springdoc)
springdoc.swagger-ui.path=/swagger-ui